# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: XDC Community Portal
            image:
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: XDC Community Portal
                image:
            copyright: Copyright &copy; 2022. - XDC Community <br>All rights reserved.
        social_list:
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/company/xdc-foundation'
            - network_name: twitter
              profile_url: 'https://twitter.com/XDCFoundation'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCXAAtlD-CRraNJKzDTF4pfg'
            - network_name: github
              profile_url: 'https://github.com/XDCFoundation'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: xdc-community # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/