- title: Frequently Asked Questions
  icon: /assets/images/service-icon2.png
  description: Explore a list of common questions to gain quick access to information.
  button_label: Read FAQ
  url: /pages/faq/
  
- title: Challenges
  icon: /assets/images/challenges-icon.png
  description:  Learn fundamental and advanced skills by actually coding.
  button_label: Level Up
  url: /pages/challenges/
  
- title: Documentation
  icon: /assets/images/service-icon3.png
  description:  Read detailed documentation, explore tutorials, and look at sample code.
  button_label: Read Docs
  url: /docs/left-sidebar-example
  